"""Per-command parser and execution modules for the Fura CLI."""

from furatena.cli.commands import (
    activation,
    agent_diff,
    api_diff,
    author,
    check,
    content,
    docs_inventory,
    docs_quality,
    docs_reference,
    evals,
    export,
    freeze,
    impact,
    init,
    mcp,
    migrate,
    pdf,
    promotion,
    query,
    recipes,
    scorecard,
    serve,
    stop,
    theme,
)
from furatena.cli.commands._shared import CommandModule

COMMANDS: tuple[CommandModule, ...] = (
    init.COMMAND,
    serve.COMMAND,
    stop.COMMAND,
    freeze.COMMAND,
    export.COMMAND,
    pdf.COMMAND,
    promotion.COMMAND,
    query.COMMAND,
    check.COMMAND,
    content.COMMAND,
    docs_inventory.COMMAND,
    docs_quality.COMMAND,
    docs_reference.COMMAND,
    agent_diff.COMMAND,
    api_diff.COMMAND,
    impact.COMMAND,
    activation.COMMAND,
    scorecard.COMMAND,
    recipes.COMMAND,
    evals.COMMAND,
    mcp.COMMAND,
    author.COMMAND,
    theme.COMMAND,
    migrate.COMMAND,
)

__all__ = ["COMMANDS", "CommandModule"]
